### ISSUE TITLE
Release did not get released

### ISSUE THREAD

**Issue by gpgekko** [sbt/sbt-gzip#14]
The releases page says that there is a 1.0.1 version, but I can't seem to find it in any repository?

**Comment by gpgekko** [comment]
@richdougherty I see you just updated the Readme to reference this release, but I still can't find it.

**Comment by richdougherty** [comment]
It should be visible now, can you try again?

**Comment by gpgekko** [comment]
Works now! Thanks

**Comment by richdougherty** [comment]
No problem :)
