### ISSUE TITLE
Include license in build artifacts

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-gzip#8]
For an example see: https://github.com/rtimush/sbt-updates/blob/master/publish.sbt#L9

**Comment by jroper** [comment]
`sbt-web-build-base` adds the license to all projects that use it, confirmed that it's correctly being added here:

https://bintray.com/sbt-web/sbt-plugin-releases/sbt-gzip#files/com.typesafe.sbt%2Fsbt-gzip%2Fscala_2.12%2Fsbt_1.0%2F1.0.2%2Fivys
